@startuml
!include Style.puml
title Class Connectivity Diagram
component "Application" {
    component 'SecureNUS {
        package "command" {
            node Commands
        }
        package secureNUS {
            node SecureNUS
        }
    }

    component UI {
        package "ui" {
            node Ui
            node Parser
            Ui -> Parser
        }

    }

    Parser -right-> Commands

    component 'Backend {
        package secureNUS {
            node Backend
        }
    }
    component SecretStorage {
        package SecretStorage {
            node SecretMaster
            node SecretEnumerator
            node SecretSearcher
        }
    }

    Commands --> SecureNUS
    SecureNUS --> SecretMaster
    SecretMaster --> SecretSearcher
    SecretMaster --> SecretEnumerator
    SecretMaster <-right-> Backend

}
component InputCLI {
    actor User
}
component Logger {
    node secure.SecureNUSLogger
    node secure.SecureNUSLoggerFormatter
    SecureNUSLogger --> SecureNUSLoggerFormatter
}
component OutputFiles {
    file logFiles
    file database
}
Application --> SecureNUSLogger
SecureNUSLoggerFormatter --> logFiles
User --> Ui
Backend <-> database
@enduml