@startuml
!include Style.puml

package Application {
    rectangle Commands
    class Parser {
    }
    class UI {
    }
    Commands <- Parser
    Parser <- UI
    Commands --> SecureNUS
    SecureNUS --> SecretMaster
    SecretMaster --> SecretSearcher
    SecretMaster --> SecretEnumerator
    SecretMaster <-> Backend
}
actor InputCLI.User
file OutputFile.database
InputCLI.User -> UI
Backend <-> OutputFile.database

@enduml