@startuml
'https://plantuml.com/component-diagram

circle "user"

rectangle "SecureNUS Application" {
    rectangle "<u>secureNUS:SecureNUS"
    "user" -u-> "<u>secureNUS:SecureNUS"
    rectangle "Parser"
    "<u>secureNUS:SecureNUS" -r-> "Parser" : parse(command, usedNames, folders)
    rectangle "<u>:ListCommand"
    "Parser" -u-> "<u>:ListCommand"

'    "<u>secureNUS:SecureNUS" -r-> "<u>:ListCommand":execute(command)
'    rectangle "<u>basicPasswordData:BasicPassword"
'    "<u>:ListCommand" -u-> "<u>basicPasswordData:BasicPassword"
''
'    rectangle "<u>secureNUSData:SecretMaster"
'    "<u>:ListCommand" -d-> "<u>secureNUSData:SecretMaster": listSecrets(folderName)
'    "<u>:ListCommand" -d-> "<u>secureNUSData:SecretMaster": getSecretTypeInfo(secret)
'    rectangle "Backend"
'    "<u>secureNUS:SecureNUS" -r-> "Backend": updateStorage(ArrayList<Secret>)
'    rectangle "System out"
'    "<u>:ListCommand" -d-> "System out":println("List ...")
}

@enduml