@startuml
'https://plantuml.com/component-diagram

circle "user"

rectangle "SecureNUS Application" {
    rectangle "<u>secureNUS:SecureNUS"
    "user" -r-> "<u>secureNUS:SecureNUS"
'    rectangle "<u>:Parser"
'    "<u>secureNUS:SecureNUS" -r-> "<u>:Parser" : parse(command, usedNames, folders)
    rectangle "<u>:DeleteCommand"
'    "<u>:Parser" -u-> "<u>:DeleteCommand"

    "<u>secureNUS:SecureNUS" -r-> "<u>:DeleteCommand":execute(command)
'    rectangle "<u>basicPasswordData:BasicPassword"
'    "<u>:DeleteCommand" -u-> "<u>basicPasswordData:BasicPassword"
''
    rectangle "<u>secureNUSData:SecretMaster"
    "<u>:DeleteCommand" -d-> "<u>secureNUSData:SecretMaster": removeSecret(deleteData)
'    rectangle "<u>:Backend"
'    "<u>secureNUS:SecureNUS" -r-> "<u>:Backend": updateStorage(ArrayList<Secret>)
}

@enduml