@startuml
'https://plantuml.com/component-diagram

circle "user"

rectangle "SecureNUS Application" {
    rectangle "<u>secureNUS:SecureNUS"
    "user" -u-> "<u>secureNUS:SecureNUS"
    rectangle "Parser"
    "<u>secureNUS:SecureNUS" -r-> "Parser" : parse(command, usedNames, folders)
    rectangle "<u>:AddBasicPasswordCommand"
    "Parser" -u-> "<u>:AddBasicPasswordCommand"

'    "<u>secureNUS:SecureNUS" -r-> "<u>:AddBasicPasswordCommand":execute(command)
'    rectangle "<u>:BasicPassword"
'    "<u>:AddBasicPasswordCommand" -u-> "<u>:BasicPassword"
''
'    rectangle "<u>secureNUSData:SecretMaster"
'    "<u>:AddBasicPasswordCommand" -d-> "<u>secureNUSData:SecretMaster": addSecret(BasicPassword)
'    rectangle "Backend"
'    "<u>secureNUS:SecureNUS" -r-> "Backend": updateStorage(ArrayList<Secret>)
}

@enduml