@startuml
!include Style.puml
title SecretStorage Component Diagram
node Backend
frame SecretStorage {
    rectangle SecretMaster
    rectangle SecretSearcher
    rectangle SecretEnumerator
    SecretMaster -[dotted]-> SecretEnumerator: alters
    SecretMaster -[dotted]-> SecretSearcher: alters
}
() SecureNUS -[dotted]right-> SecretMaster :requests alteration \n of data via
SecretMaster <-[dotted]right-> Backend : sends data for export OR\n collects data for import
@enduml