@startuml
!include Style.puml
title UI Component Diagram
actor User
node SecureNUS
node SecretStorage
component "UI" {
    rectangle Ui UI_COLOR
    rectangle Parser
    Ui -> Parser
}
rectangle Commands COMMAND_COLOR
Parser -[dotted]-> Commands :creates
Commands -[dotted]right-> SecureNUS :executes in
SecureNUS <-[dotted]up-> SecretStorage :reads or writes data from
SecureNUS -[dotted]up-> Ui :responds to user after processing through
Ui <-up-> User
@enduml