@startuml
package UI {
    class Ui {
        {static}+ in: Scanner
        {static}+ greetUser(): void
        {static}+ printLine(): void
        {static}+ print(line: String): void
        {static}+ readCommand(): void
        {static}+ readLine(): void
        {static}+ printError(message): void
        {static}+ close(): void
    }
    class Parser {
        {static}+ parse(): Command
        {static}+ parseAdd(): Command
    }
    Parser -[dotted]> Ui
}
@enduml