@startuml
'https://plantuml.com/class-diagram
skinparam groupInheritance 4

allowmixing

file File
Backend --l> File
class Backend {
    {static} - ENCRYPTION_IDENTIFIER
    {static} - DATABASE_FOLDER
    {static} - DATABASE_FILE
    {static} + initialisation(): SecretMaster
    {static} + readAndUpdate(String[], ArrayList<Secret>): ArrayList<Secret>
    {static} + createFolderHashtable(ArrayList<Secret>): Hashtable<String, (ArrayList<Secret>))
    {static} + createNameHashtable(ArrayList<Secret>): Hashtable<String, Secret>
    {static} + createHashTableFolders(Hashtable<String, ArrayList<Secret>>): Hashtable<String, Hashtable<String, Secret>>
    {static} + encode(String): String
    {static} + decode(String): String
    {static} + parseEmptyField(String): String
    {static} + updateStorage(ArrayList<Secret>): void
}
package storage {
    Backend --> SecretMaster
    Backend --> SecretSearcher
    Backend --> SecretEnumerator
    class SecretMaster {
    }
    class SecretSearcher {
    }
    class SecretEnumerator {
    }
}
package Secret {

    Backend --u> StudentID
    Backend --u> NUSNet
    Backend --u> BasicPassword
    Backend --u> CreditCard
    Backend --u> CryptoWallet
    Backend --u> WifiPassword

    class Secret {
    }
    class StudentID {
    }
    class NUSNet {
    }
    class BasicPassword {
    }
    class CreditCard {
    }
    class CryptoWallet {
    }
    class WifiPassword {
    }
    class BasicPassword {
    }
    StudentID --u|> Secret
    NUSNet --u|> Secret
    BasicPassword --u|> Secret
    CryptoWallet --u|> Secret
    CreditCard --u|> Secret
    WifiPassword --u|> Secret
}


@enduml