!include Style.puml
@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

actor User #FFFBBB
User-> ":Ui" #FFBBBB: "new password"
":Ui" -> ":SecureNUS" #FFBFFF
":SecureNUS" -> ":Parser"#BBFFFF: parse()
":Parser" -> ":Command" **
activate ":Command"#BBB
":Command"-> ":Command"#FFFAAA:extractName()
return
":Command"-> ":Command"#FFFAAA:extractFolderName()
return
":Command"-> ":Command"#FFFAAA:inquireURL()
return
":Command"-> ":Command"#FFFAAA:inquireUsername()
return
":Command"-> ":Command"#FFFAAA:inquirePassword()
return
return
return
":SecureNUS" -> ":Command"#FFAFFF:execute()
":Command" -> ":SecretStorage"#FFAAFF:addSecret()
":SecretStorage" -> ":SecretStorage"#11AF1F:add()
return

return
return
":SecureNUS" -> ":Backend"#FFAF1F:updateStorage()
return
return
return Added!
@enduml